package com.views;

import com.bean.TradeBean;
import com.data.Data;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ConfirmScreen {
    private JPanel ConfirmScreen;
    JFrame frame;
    String[] headers = {"Type", "Description", "ID required", "Discount"};
    Object[][] cellData = {{"Type", "Description", "ID required", "Discount"},
            {"Child", "2-17 years old", "None", "50%"},
            {"Adult", "18 years older", "None", "None"},
            {"Senior", "55 years older", "None", "20%"},
            {"Student", "18 years old and full-time education", "Student ID", "15%"}};
    private JTable table1;
    private JButton childButton;
    private JButton adultButton;
    private JButton seniorButton;
    private JButton studentButton;
    private JTextField priceField;
    private JTextField typeField;
    private JTextField studentIDField;
    private JButton button1;
    private ButtonActionListener buttonActionListener = new ButtonActionListener();


    public ConfirmScreen() {
        frame = new JFrame("ConfirmScreen");
        $$$setupUI$$$();
        frame.setContentPane(this.ConfirmScreen);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(600, 600);
        frame.setVisible(true);

        studentIDField.setEditable(false);

        childButton.addActionListener(buttonActionListener);
        adultButton.addActionListener(buttonActionListener);
        seniorButton.addActionListener(buttonActionListener);
        studentButton.addActionListener(buttonActionListener);
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                TradeBean tradeBean = Data.tradeBeanArrayList.get(Data.tradeBeanArrayList.size() - 1);
                if (tradeBean.getTicketType().equals("Student")) {
                    if (studentIDField.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Student id can't be null", "alert", JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {
                        int studentID = Integer.parseInt(studentIDField.getText());
                        tradeBean.setStudentNumber(studentID);
                    }
                }
                new TicketDetail();
                frame.setVisible(false);
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable(cellData, headers);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        ConfirmScreen = new JPanel();
        ConfirmScreen.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        ConfirmScreen.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Choose your identity");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        ConfirmScreen.add(label1, gbc);
        table1.setAutoResizeMode(4);
        table1.setFillsViewportHeight(false);
        table1.setSurrendersFocusOnKeystroke(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 9;
        gbc.fill = GridBagConstraints.BOTH;
        ConfirmScreen.add(table1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Price");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        ConfirmScreen.add(label2, gbc);
        priceField = new JTextField();
        priceField.setEditable(false);
        priceField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(priceField, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        ConfirmScreen.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Steudent ID");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        ConfirmScreen.add(label4, gbc);
        typeField = new JTextField();
        typeField.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(typeField, gbc);
        studentIDField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(studentIDField, gbc);
        childButton = new JButton();
        childButton.setText("Child");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(childButton, gbc);
        adultButton = new JButton();
        adultButton.setText("Adult");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(adultButton, gbc);
        seniorButton = new JButton();
        seniorButton.setText("Senior");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(seniorButton, gbc);
        studentButton = new JButton();
        studentButton.setText("Student");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(studentButton, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        ConfirmScreen.add(spacer2, gbc);
        button1 = new JButton();
        button1.setText("Confirm");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(button1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        ConfirmScreen.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ConfirmScreen.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        ConfirmScreen.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        ConfirmScreen.add(spacer9, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ConfirmScreen;
    }

    private class ButtonActionListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            studentIDField.setEditable(false);
            TradeBean tradeBean = Data.tradeBeanArrayList.get(Data.tradeBeanArrayList.size() - 1);
            tradeBean.setTicketType(e.getActionCommand());
            typeField.setText(e.getActionCommand());
            int price = 16;
            if (e.getSource() == childButton) {
                price = 8;
            }
            if (e.getSource() == studentButton) {
                price = 14;
                studentIDField.setEditable(true);
            }
            if (e.getSource() == seniorButton) {
                price = 13;
            }
            tradeBean.setPrice(price);
            priceField.setText(String.valueOf(price));

        }
    }


}
