package com.views;

import com.bean.TradeBean;
import com.data.Data;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Field;

/*************************************************************************
> File Name: 
> Author: shihang
> Mail: shihangTs@gmail.com
> Created Time: 2017.04.04 
> Description: 
************************************************************************/

public class Screen2 extends Screen {
    private JPanel Screen2;
    private JButton d5;
    private JButton d8;
    private JButton d7;
    private JButton d6;
    private JButton d4;
    private JButton d3;
    private JButton d2;
    private JButton d1;
    private JButton c6;
    private JButton c5;
    private JButton c4;
    private JButton c3;
    private JButton c2;
    private JButton c1;
    private JButton b6;
    private JButton b5;
    private JButton b4;
    private JButton b3;
    private JButton b2;
    private JButton b1;
    private JButton a6;
    private JButton a5;
    private JButton a4;
    private JButton a3;
    private JButton a2;
    private JButton a1;

    public Screen2() {
        frame = new JFrame("Screen2");
        frame.setContentPane(this.Screen2);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(600, 600);
        frame.setVisible(true);
        addListener();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Screen2 = new JPanel();
        Screen2.setLayout(new GridBagLayout());
        d8 = new JButton();
        d8.setText("d8");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d8, gbc);
        c6 = new JButton();
        c6.setText("c6");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c6, gbc);
        c5 = new JButton();
        c5.setText("c5");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c5, gbc);
        b6 = new JButton();
        b6.setText("b6");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b6, gbc);
        b5 = new JButton();
        b5.setText("b5");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b5, gbc);
        a6 = new JButton();
        a6.setText("a6");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a6, gbc);
        a5 = new JButton();
        a5.setText("a5");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a5, gbc);
        c2 = new JButton();
        c2.setText("c2");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c2, gbc);
        c4 = new JButton();
        c4.setText("c4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c4, gbc);
        c1 = new JButton();
        c1.setText("c1");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c1, gbc);
        c3 = new JButton();
        c3.setText("c3");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(c3, gbc);
        b2 = new JButton();
        b2.setText("b2");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b2, gbc);
        b4 = new JButton();
        b4.setText("b4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b4, gbc);
        b1 = new JButton();
        b1.setText("b1");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b1, gbc);
        b3 = new JButton();
        b3.setText("b3");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(b3, gbc);
        a2 = new JButton();
        a2.setText("a2");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a2, gbc);
        a4 = new JButton();
        a4.setText("a4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a4, gbc);
        a1 = new JButton();
        a1.setText("a1");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a1, gbc);
        a3 = new JButton();
        a3.setText("a3");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(a3, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        Screen2.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        Screen2.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        Screen2.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        Screen2.add(spacer5, gbc);
        d1 = new JButton();
        d1.setText("d1");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d1, gbc);
        d2 = new JButton();
        d2.setText("d2");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d2, gbc);
        d3 = new JButton();
        d3.setText("d3");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d3, gbc);
        d4 = new JButton();
        d4.setText("d4");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d4, gbc);
        d5 = new JButton();
        d5.setText("d5");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d5, gbc);
        d6 = new JButton();
        d6.setText("d6");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d6, gbc);
        d7 = new JButton();
        d7.setText("d7");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Screen2.add(d7, gbc);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-16726040));
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 24));
        label1.setText("Screen");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.gridwidth = 3;
        Screen2.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Screen2;
    }
}
